version: '3.9'

services:
  labelbox:
    image: labelbox
    container_name: labelbox
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5888:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CorsAttribute_Headers=*
      - CorsAttribute_Methods=*
      - CorsAttribute_Origins=*
      - AllowedHosts=*
    volumes:
      - type: bind
        source: ./images
        target: /images
  labelbox-tests:
    image: labelbox-tests
    container_name: labelbox-tests
    build:
      context: .
      dockerfile: Tests.Dockerfile